replicaCount: 2

image:
  repository: farrukhdock/java
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: helloworldapp-service
  type: ClusterIP
  port: 9090
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: domain.com
      paths:
        - path: /
          pathType: Prefix
          service:
            name: helloworldapp-service
            port: 9090
        - path: /image
          pathType: Prefix
          service:
            name: helloworldapp-service
            port: 9090
  tls:
    - secretName: cert-file
      hosts:
        - domain.com

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
